name: Post Instagram Picture

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  post_picture:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver_manager

    - name: Post Instagram Picture
      env:
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        PICTURE_PATH: "pictures/6Oy2Bt1Iq3Rp.png"
      run: |
        python post_instagram_picture.py
